sudo: required
dist: trusty
language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGOVER=django21 CMSVER=cms36
  - DJANGOVER=django22 CMSVER=cms36
  - DJANGOVER=django22 CMSVER=cms37
  - DJANGOVER=django30 CMSVER=cms37
  - DJANGOVER=django22 CMSVER=cms40
  - DJANGOVER=django30 CMSVER=cms40

matrix:
  allow_failures:
    - python: 3.8
      env: DJANGOVER=django21 CMSVER=cms36
    - python: 3.8
      env: DJANGOVER=django22 CMSVER=cms36
    - python: 3.8
      env: DJANGOVER=django30 CMSVER=cms37

before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  
install:
  - pip install tox

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}-${CMSVER}
  - tox -e "$TOX_ENV"
