# Generated by Django 2.2.10 on 2020-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0027_version_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeClipboardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CascadeClipboardProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cmsplugin_cascade.cascadeclipboard',),
        ),
        migrations.CreateModel(
            name='CascadeClipboardGroupProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cmsplugin_cascade.cascadeclipboardgroup',),
        ),
        migrations.AddField(
            model_name='cascadeclipboard',
            name='group',
            field=models.ManyToManyField(to='cmsplugin_cascade.CascadeClipboardGroup'),
        ),
    ]
